import React, { useState } from "react";
import {
  CheckCircle,
  AlertTriangle,
  XCircle,
  TrendingUp,
  Download,
  User,
  Shield,
  FileText,
} from "lucide-react";
import ProgressBar from "./ProgressBar";
import NextPreparerModal from "./NextPreparerModal";
import { authorityLevels } from "../data/formData";
import {
  downloadCSV,
  getAppraisalDecisionColor,
  getHeaderColor,
} from "../utils";
import { useNextPreparerModal } from "../hooks";

const approvalOptions = [
  {
    value: "Approve",
    label: "Approve",
    icon: CheckCircle,
    color: "text-emerald-600",
    activeClass: "bg-emerald-50 border-emerald-200 shadow-sm",
  },
  {
    value: "Approve with Conditions",
    label: "Approve with Conditions",
    icon: AlertTriangle,
    color: "text-amber-600",
    activeClass: "bg-amber-50 border-amber-200 shadow-sm",
  },
  {
    value: "Reject",
    label: "Reject",
    icon: XCircle,
    color: "text-red-600",
    activeClass: "bg-red-50 border-red-200 shadow-sm",
  },
  {
    value: "Escalate",
    label: "Escalate",
    icon: TrendingUp,
    color: "text-purple-600",
    activeClass: "bg-purple-50 border-purple-200 shadow-sm",
  },
];

const preparerOptions = [
  { value: "user1", label: "Sarah Connor (Risk Manager)" },
  { value: "user2", label: "John Smith (Credit Officer)" },
  { value: "user3", label: "Emily Chen (ESG Specialist)" },
];

const AppraisalStep: React.FC = () => {
  const [approvalDecision, setApprovalDecision] = useState("Approve");
  const [approver, setApprover] = useState("");
  const [approvalAuthority, setApprovalAuthority] = useState("ESG Officer");
  const [finalComments, setFinalComments] = useState("");

  const {
    showModal,
    nextPreparer,
    notificationSent,
    setNextPreparer,
    openModal,
    closeModal,
    handleSubmit,
  } = useNextPreparerModal();

  const downloadApprovalReport = () => {
    const reportData = [
      ["BOI ESRM - Step 5: Appraisal & Conditions Report"],
      ["Generated on:", new Date().toLocaleDateString()],
      [""],
      ["Approval Decision:", approvalDecision],
      ["Approver:", approver || "Not specified"],
      ["Approval Authority Level:", approvalAuthority],
      [""],
      ["Final Comments from Risk Reviewer:"],
      [finalComments || "No comments provided"],
      [""],
      ["Report generated by BOI ESRM Tool"],
    ];

    downloadCSV(reportData, "Approval_Report.csv");
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 transition-colors duration-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="bg-white dark:bg-slate-800 rounded-lg shadow-sm border border-slate-200 dark:border-slate-700">
          <div className="border-b border-slate-200 dark:border-slate-700 bg-slate-900 px-6 py-5 rounded-t-lg">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-2xl font-bold text-white flex items-center gap-2">
                  <Shield className="w-6 h-6 text-[#86BC25]" />
                  Step 5: Appraisal & Conditions
                </h1>
                <p className="text-slate-300 mt-1 text-sm">
                  Summarize E&S risk, define approval decision, conditions, and
                  obtain sign-off.
                </p>
              </div>
              <button
                onClick={openModal}
                className="px-4 py-2 bg-[#86BC25] hover:bg-[#6B9B1E] text-slate-900 rounded-md transition-colors flex items-center gap-2 font-medium text-sm shadow-sm cursor-pointer"
              >
                <User className="w-4 h-4" />
                Select Next Preparer
              </button>
            </div>
          </div>

          <div className="p-6 space-y-8">
            <ProgressBar currentStep={5} />

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              <div className="lg:col-span-2 space-y-6">
                <div
                  className={`bg-white dark:bg-slate-800 rounded-lg border shadow-sm overflow-hidden ${getHeaderColor(approvalDecision)} border-slate-200 dark:border-slate-700`}
                >
                  <div className="bg-slate-50 dark:bg-slate-800/50 px-6 py-4 border-b border-slate-100 dark:border-slate-700 flex items-center gap-3">
                    <CheckCircle className="w-5 h-5 text-slate-500" />
                    <h3 className="font-bold text-lg text-slate-900 dark:text-white">
                      Approval Decision
                    </h3>
                  </div>

                  <div
                    className={`p-6 transition-colors duration-300 ${getAppraisalDecisionColor(approvalDecision)} bg-opacity-30 dark:bg-opacity-10`}
                  >
                    <div className="space-y-6">
                      <div>
                        <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-4">
                          Final decision from the ESRM review
                        </label>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                          {approvalOptions.map((option) => {
                            const Icon = option.icon;
                            const isSelected =
                              approvalDecision === option.value;
                            return (
                              <label
                                key={option.value}
                                className={`
                                  flex items-center gap-3 cursor-pointer p-3 rounded-lg border transition-all
                                  ${
                                    isSelected
                                      ? `${option.activeClass} dark:bg-opacity-20`
                                      : "border-slate-200 dark:border-slate-600 hover:bg-slate-50 dark:hover:bg-slate-700/50"
                                  }
                                `}
                              >
                                <input
                                  type="radio"
                                  name="approvalDecision"
                                  value={option.value}
                                  checked={isSelected}
                                  onChange={(e) =>
                                    setApprovalDecision(e.target.value)
                                  }
                                  className="w-4 h-4 text-[#86BC25] border-slate-300 focus:ring-[#86BC25] cursor-pointer"
                                />
                                <Icon className={`w-5 h-5 ${option.color}`} />
                                <span
                                  className={`text-sm font-medium ${isSelected ? "text-slate-900 dark:text-white" : "text-slate-600 dark:text-slate-400"}`}
                                >
                                  {option.label}
                                </span>
                              </label>
                            );
                          })}
                        </div>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                          <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">
                            Approver Name / Committee
                          </label>
                          <input
                            type="text"
                            value={approver}
                            onChange={(e) => setApprover(e.target.value)}
                            className="w-full px-4 py-2.5 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-[#86BC25] focus:border-transparent bg-white dark:bg-slate-800 text-slate-900 dark:text-white"
                            placeholder="e.g. John Doe"
                          />
                        </div>

                        <div>
                          <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">
                            Approval Authority Level
                          </label>
                          <div className="relative">
                            <select
                              value={approvalAuthority}
                              onChange={(e) =>
                                setApprovalAuthority(e.target.value)
                              }
                              className="w-full px-4 py-2.5 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-[#86BC25] focus:border-transparent appearance-none bg-white dark:bg-slate-800 text-slate-900 dark:text-white pr-10 cursor-pointer"
                            >
                              {authorityLevels.map((level) => (
                                <option key={level} value={level}>
                                  {level}
                                </option>
                              ))}
                            </select>
                            <div className="absolute inset-y-0 rit-0 flex items-center px-3 pointer-events-none text-slate-500">
                              <svg
                                className="w-4 h-4"
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                              >
                                <path
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeWidth={2}
                                  d="M19 9l-7 7-7-7"
                                />
                              </svg>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm overflow-hidden">
                  <div className="bg-slate-50 dark:bg-slate-800/50 px-6 py-4 border-b border-slate-100 dark:border-slate-700 flex items-center gap-3">
                    <FileText className="w-5 h-5 text-slate-500" />
                    <h3 className="font-bold text-lg text-slate-900 dark:text-white">
                      Final Comments & Rationale
                    </h3>
                  </div>
                  <div className="p-6">
                    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-3">
                      Reviewer Comments
                    </label>
                    <textarea
                      value={finalComments}
                      onChange={(e) => setFinalComments(e.target.value)}
                      rows={6}
                      className="w-full px-4 py-3 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-[#86BC25] focus:border-transparent text-slate-900 dark:text-white bg-white dark:bg-slate-800 resize-none"
                      placeholder="Enter final comments, specific conditions, or rationale for the decision..."
                    />
                    <div className="mt-4 flex justify-end">
                      <button
                        onClick={downloadApprovalReport}
                        className="inline-flex items-center gap-2 px-4 py-2 bg-slate-900 dark:bg-slate-700 hover:bg-slate-800 dark:hover:bg-slate-600 text-white rounded-md transition-colors text-sm font-medium cursor-pointer"
                      >
                        <Download className="w-4 h-4" />
                        Download PDF Report
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              <div className="lg:col-span-1">
                <div className="bg-slate-50 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700 p-6 sticky top-6">
                  <div className="flex items-center gap-3 mb-6">
                    <Shield className="w-6 h-6 text-[#86BC25]" />
                    <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                      Appraisal Summary
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="p-4 bg-white dark:bg-slate-800 rounded-md border border-slate-100 dark:border-slate-700 shadow-sm">
                      <span className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">
                        Decision
                      </span>
                      <div
                        className={`text-lg font-bold ${
                          approvalDecision === "Approve"
                            ? "text-emerald-600"
                            : approvalDecision === "Reject"
                              ? "text-red-600"
                              : approvalDecision === "Escalate"
                                ? "text-purple-600"
                                : "text-amber-600"
                        }`}
                      >
                        {approvalDecision}
                      </div>
                    </div>

                    <div className="p-4 bg-white dark:bg-slate-800 rounded-md border border-slate-100 dark:border-slate-700 shadow-sm">
                      <span className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">
                        Authority
                      </span>
                      <div className="text-slate-900 dark:text-white font-medium">
                        {approvalAuthority}
                      </div>
                    </div>

                    <div className="p-4 bg-white dark:bg-slate-800 rounded-md border border-slate-100 dark:border-slate-700 shadow-sm">
                      <span className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">
                        Approver
                      </span>
                      <div className="text-slate-900 dark:text-white font-medium">
                        {approver || "Pending..."}
                      </div>
                    </div>

                    <div className="p-4 bg-white dark:bg-slate-800 rounded-md border border-slate-100 dark:border-slate-700 shadow-sm">
                      <span className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">
                        Date
                      </span>
                      <div className="text-slate-900 dark:text-white font-medium">
                        {new Date().toLocaleDateString()}
                      </div>
                    </div>
                  </div>

                  <div className="mt-8 pt-6 border-t border-slate-200 dark:border-slate-700">
                    <button className="w-full py-2.5 bg-[#86BC25] hover:bg-[#6B9B1E] text-slate-900 font-bold rounded-lg shadow-md transition-all flex items-center justify-center gap-2 cursor-pointer">
                      <CheckCircle className="w-5 h-5" />
                      Finalize Appraisal
                    </button>
                    <p className="text-xs text-center text-slate-500 mt-3">
                      This will lock the appraisal and notify stakeholders.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <NextPreparerModal
        showModal={showModal}
        nextPreparer={nextPreparer}
        notificationSent={notificationSent}
        onClose={closeModal}
        onSubmit={handleSubmit}
        onPreparerChange={setNextPreparer}
        preparerOptions={preparerOptions}
      />
    </div>
  );
};

export default AppraisalStep;
