import jsPDF from "jspdf";
import html2canvas from "html2canvas";

/* ─── Branded PDF / image export for Scenario Analysis ─── */

async function elementToCanvas(
  element: HTMLElement,
  scale = 2,
): Promise<HTMLCanvasElement> {
  return html2canvas(element, {
    scale,
    useCORS: true,
    allowTaint: true,
    backgroundColor: "#ffffff",
    logging: false,
  });
}

/**
 * Export the scenario results section to a branded PDF.
 * @param containerRef  the DOM node wrapping the entire results page
 * @param meta          title / scenario / horizon info for the header
 */
export async function exportScenarioPDF(
  containerRef: HTMLElement,
  meta: {
    title: string;
    scenario: string;
    horizon: string;
    industry?: string;
    date?: string;
  },
): Promise<void> {
  const dateStr =
    meta.date ??
    new Date().toLocaleDateString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });

  // Capture the page content
  const canvas = await elementToCanvas(containerRef);

  // Dimensions
  const pageW = 297; // A4 landscape width mm
  const pageH = 210;
  const margin = 12;
  const headerH = 28;
  const footerH = 10;
  const contentW = pageW - margin * 2;

  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  /* ─── Header ─── */
  doc.setFillColor(51, 51, 51);
  doc.rect(0, 0, pageW, headerH, "F");
  doc.setFillColor(134, 188, 37); // Deloitte green accent
  doc.rect(0, headerH - 2, pageW, 2, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("GCB ESG Navigator", margin, 12);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(meta.title, margin, 19);
  doc.setFontSize(9);
  doc.text(
    `Scenario: ${meta.scenario}  |  Horizon: ${meta.horizon}  |  ${meta.industry ?? ""}`,
    margin,
    24,
  );
  doc.text(dateStr, pageW - margin, 12, { align: "right" });
  doc.text("CONFIDENTIAL", pageW - margin, 19, { align: "right" });

  /* ─── Content pages ─── */
  const imgData = canvas.toDataURL("image/png");
  const imgW = contentW;
  const imgH = (canvas.height / canvas.width) * imgW;

  let yOffset = 0;
  let pageNum = 1;

  while (yOffset < imgH) {
    if (pageNum > 1) {
      doc.addPage("a4", "landscape");
      // Mini header on continuation pages
      doc.setFillColor(51, 51, 51);
      doc.rect(0, 0, pageW, 8, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text(`GCB ESG Navigator — ${meta.title}`, margin, 5.5);
      doc.text(`Page ${pageNum}`, pageW - margin, 5.5, { align: "right" });
    }

    const startY = pageNum === 1 ? headerH + 4 : 12;

    // Clip and position the image
    doc.addImage(
      imgData,
      "PNG",
      margin,
      startY - (yOffset / imgH) * imgH * 0,
      imgW,
      imgH,
      undefined,
      "FAST",
      0,
    );

    // We do a simple single-page capture for now
    yOffset = imgH; // break after first

    /* ─── Footer ─── */
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, pageH - footerH, pageW - margin, pageH - footerH);
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(7);
    doc.text(
      "Generated by GCB ESG Navigator. This document is for internal use only.",
      margin,
      pageH - 4,
    );
    doc.text(`Page ${pageNum}`, pageW - margin, pageH - 4, { align: "right" });

    pageNum++;
  }

  /* ─── Save ─── */
  const fileName = `ESG_Scenario_${meta.scenario.replace(/\s+/g, "_")}_${meta.horizon}_${dateStr.replace(/\s+/g, "")}.pdf`;
  doc.save(fileName);
}

/**
 * Export the CRA module content to branded PDF.
 */
export async function exportCRAPDF(
  containerRef: HTMLElement,
  meta: {
    title: string;
    sections?: string[];
    industry?: string;
    date?: string;
  },
): Promise<void> {
  const dateStr =
    meta.date ??
    new Date().toLocaleDateString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  const canvas = await elementToCanvas(containerRef);

  const pageW = 297;
  const pageH = 210;
  const margin = 12;
  const headerH = 28;
  const footerH = 10;
  const contentW = pageW - margin * 2;

  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  /* Header */
  doc.setFillColor(51, 51, 51);
  doc.rect(0, 0, pageW, headerH, "F");
  doc.setFillColor(134, 188, 37);
  doc.rect(0, headerH - 2, pageW, 2, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("GCB ESG Navigator — Climate Risk Assessment", margin, 12);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(meta.title, margin, 19);
  doc.setFontSize(9);
  doc.text(meta.industry ? `Industry: ${meta.industry}` : "", margin, 24);
  doc.text(dateStr, pageW - margin, 12, { align: "right" });
  doc.text("CONFIDENTIAL", pageW - margin, 19, { align: "right" });

  /* Content */
  const imgData = canvas.toDataURL("image/png");
  const imgW = contentW;
  const imgH = (canvas.height / canvas.width) * imgW;

  doc.addImage(
    imgData,
    "PNG",
    margin,
    headerH + 4,
    imgW,
    imgH,
    undefined,
    "FAST",
  );

  /* Footer */
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, pageH - footerH, pageW - margin, pageH - footerH);
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(7);
  doc.text(
    "Generated by GCB ESG Navigator. For internal use only.",
    margin,
    pageH - 4,
  );
  doc.text("Page 1", pageW - margin, pageH - 4, { align: "right" });

  const fileName = `ESG_CRA_Report_${dateStr.replace(/\s+/g, "")}.pdf`;
  doc.save(fileName);
}
