import type { SRROItem } from "@/store/sustainabilityStore";

// CRRO refs (climate-related risks/opportunities) from Phase 3 Final List
const CRRO_REFS = new Set(["021", "026", "027", "028", "035", "070"]);

function srro(
  ref: string,
  source: string,
  title: string,
  description: string,
  type: "Risk" | "Opportunity",
  stage: "Upstream" | "Core" | "Downstream",
  fin: "Yes" | "No",
  str: "Yes" | "No",
  ops: "Yes" | "No",
  horizon: "Short" | "Medium" | "Long",
  lkh: number,
  mag: number,
  needed: "Yes" | "No",
  include: "Yes" | "No",
): SRROItem {
  return {
    id: `p3-${ref}`,
    ref,
    source,
    title,
    description,
    type,
    valueChainStage: stage,
    financialImpact: fin,
    strategicImpact: str,
    operationalImpact: ops,
    timeHorizon: horizon,
    likelihood: lkh,
    magnitude: mag,
    neededByPrimaryUser: needed,
    includeInFinalList: include,
    srroCrro: CRRO_REFS.has(ref) ? "CRRO" : "SRRO",
  };
}

export const PHASE3_INITIAL_DATA: SRROItem[] = [
  srro("001","Value chain assessment","Broker dependency risk","HGI relies on brokers for day-to-day operations, product access, business placement and sales outcomes. Weak broker relationships or broker disruption may affect distribution and revenue generation.","Risk","Upstream","Yes","Yes","Yes","Medium",4,3,"Yes","Yes"),
  srro("002","Value chain assessment","Broker network opportunity","Brokers are the most important distribution channel and broker relationships drive strong sales outcomes. A strong broker network may support market reach and business growth.","Opportunity","Downstream","Yes","Yes","Yes","Medium",3,3,"Yes","Yes"),
  srro("003","Value chain assessment","Banking service disruption risk","HGI relies on bankers for day-to-day operations, and disruption from bankers could affect operations.","Risk","Upstream","Yes","Yes","Yes","Short",2,3,"Yes","No"),
  srro("004","Value chain assessment","Software licensor dependency risk","HGI relies on a third-party licensed system; a glitch from the software licensor could disrupt day-to-day operations.","Risk","Core","Yes","Yes","Yes","Short",3,3,"Yes","Yes"),
  srro("005","Value chain assessment","Cross-border technology vendor risk","ESKADENIA is a system used by the company, and the vendor is based in Jordan. Dependency on an overseas technology vendor may expose operations to vendor availability and support risks.","Risk","Core","No","Yes","Yes","Medium",2,3,"No","No"),
  srro("006","Value chain assessment","Digital process automation opportunity","Automated systems enable processed data to flow between underwriting, claims, finance and risk, supporting operational coordination.","Opportunity","Core","Yes","Yes","Yes","Medium",2,3,"Yes","No"),
  srro("007","Value chain assessment","Survey dependency risk","Survey information is needed for some underwriting decisions; where a risk cannot be surveyed, underwriting may be difficult.","Risk","Upstream","Yes","Yes","No","Short",3,3,"Yes","Yes"),
  srro("008","Value chain assessment","Claims settlement reputational risk","Prompt claims settlement defines good customer experience, while delayed settlement may create poor customer experience. Claims payment is also sensitive to reputational risk.","Risk","Downstream","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("009","Value chain assessment","Claims service opportunity","Prompt claims settlement can improve customer experience, trust and retention.","Opportunity","Downstream","Yes","Yes","Yes","Medium",3,3,"Yes","Yes"),
  srro("010","Value chain assessment","Policy document issuance risk","Policy document issuance was identified as one of the service delivery areas sensitive to failure or reputational risk.","Risk","Core","Yes","No","Yes","Short",3,3,"Yes","Yes"),
  srro("011","Value chain assessment","Capital adequacy and underwriting capacity risk","Capital determines the volume of risks the company can carry and affects profitability and long-term goals.","Risk","Upstream","Yes","Yes","Yes","Long",3,4,"Yes","Yes"),
  srro("012","Value chain assessment","Reinsurance dependency risk","Investors and reinsurers influence capital availability and solvency; solvency risk was identified.","Risk","Upstream","Yes","Yes","Yes","Long",3,4,"Yes","Yes"),
  srro("013","Value chain assessment","Reinsurance capacity opportunity","Reinsurance supports the company's ability to carry risk and grow the business, subject to treaty agreement conditions.","Opportunity","Upstream","Yes","Yes","Yes","Long",3,3,"Yes","Yes"),
  srro("014","Value chain assessment","Regulatory recapitalisation risk","Ongoing recapitalisation was identified as a regulatory change that could meaningfully affect the business.","Opportunity","Upstream","Yes","Yes","Yes","Medium",3,4,"Yes","Yes"),
  srro("015","Value chain assessment","Motor insurance growth opportunity","Motor is identified as the product growing faster or more strategically important.","Opportunity","Core","Yes","Yes","Yes","Medium",3,3,"Yes","Yes"),
  srro("016","Value chain assessment","Oil and gas sector exposure risk","Oil and Gas is a main revenue-driving line and one of the main customer sectors, creating exposure to sector-specific underwriting and claims risks.","Risk","Core","Yes","Yes","Yes","Long",2,4,"Yes","Yes"),
  srro("017","Value chain assessment","Digital customer servicing opportunity","Most customers are serviced through digital channels, reducing reliance on physical customer visits.","Opportunity","Downstream","Yes","Yes","Yes","Medium",3,2,"No","No"),
  srro("018","Value chain assessment","Agent channel data gap risk","Retail customers are sold to mostly directly or through agents, but agent names, locations and dependency details were not provided.","Risk","Downstream","No","Yes","Yes","Medium",2,2,"No","No"),
  srro("019","Value chain assessment","Governance and risk ownership data gap","The questionnaire did not provide a response on where governance, risk and compliance sit in daily operations.","Risk","Core","No","Yes","Yes","Medium",2,3,"Yes","No"),
  srro("020","Regulators and peers","Regulatory recapitalisation risk","Ongoing recapitalisation was identified as a regulatory change that could meaningfully affect the business.","Risk","Upstream","Yes","Yes","Yes","Medium",3,4,"Yes","Yes"),
  srro("021","Regulators and peers","Climate risk supervision and resilience risk","IAIS states that climate change is a source of financial risk affecting insurer resilience and financial stability, with insurers exposed through underwriting and investment activities.","Risk","Core","Yes","Yes","Yes","Long",2,4,"Yes","Yes"),
  srro("022","Regulators and peers","ESG framework compliance readiness risk","NAICOM has indicated commitment to institutionalising ESG principles and sustainable insurance practices through an in-house ESG Framework.","Risk","Upstream","No","Yes","Yes","Medium",3,3,"No","No"),
  srro("023","Regulators and peers","Actuarial capacity development risk","NAICOM and UNDP discussions highlighted the need to strengthen systemic capacity, including actuarial development, for the Nigerian insurance sector.","Risk","Core","No","Yes","Yes","Medium",2,3,"No","No"),
  srro("024","Regulators and peers","Product design compliance risk","Regulatory requirements affect both product design and operations, but more on product design.","Risk","Upstream","Yes","Yes","Yes","Medium",3,3,"Yes","Yes"),
  srro("025","Regulators and peers","Climate and disaster risk insurance opportunity","NAICOM and UNDP are collaborating to scale climate and disaster risk solutions in Nigeria, including interest in scaling the Lagos Flood Risk Insurance Model.","Opportunity","Core","Yes","Yes","Yes","Medium",2,3,"Yes","No"),
  srro("026","IFRS S2 climate risk","Weather-related natural catastrophe exposure risk","IFRS S2 insurance guidance identifies weather-related natural catastrophe exposure as relevant for insurers, including probable maximum loss and monetary losses from modeled and non-modeled natural catastrophes.","Risk","Core","Yes","Yes","Yes","Long",2,4,"Yes","Yes"),
  srro("027","IFRS S2 climate risk","Climate impact on reinsurance cost risk","IFRS S2 insurance guidance requires discussion of how climate-change impacts and weather-related loss variability affect reinsurance cost and the insurer's risk-transfer approach.","Risk","Upstream","Yes","Yes","Yes","Long",2,4,"Yes","Yes"),
  srro("028","IFRS S2 climate risk","Transition exposure to carbon-related industries","IFRS S2 insurance guidance identifies transition-risk exposure through gross exposure to carbon-related industries and financed emissions.","Risk","Core","Yes","Yes","Yes","Long",2,4,"Yes","Yes"),
  srro("029","IFRS S2 climate risk","ESG integration in investment management opportunity","IFRS S2 insurance guidance identifies ESG incorporation in investment management as relevant because ESG factors can affect portfolio risk and risk-adjusted returns.","Opportunity","Upstream","Yes","Yes","Yes","Long",2,3,"Yes","No"),
  srro("030","SASB","Environmental risk incorporation in underwriting","SASB insurance metrics include disclosure of how environmental risks are incorporated into underwriting for individual contracts and firm-level capital adequacy.","Opportunity","Core","Yes","Yes","Yes","Long",3,3,"Yes","Yes"),
  srro("031","SASB","Low-carbon and energy-efficiency insurance opportunity","SASB identifies net premiums written for policies related to energy efficiency and low-carbon technology, including renewable energy insurance and carbon capture/storage insurance.","Opportunity","Core","Yes","Yes","Yes","Medium",2,2,"No","No"),
  srro("032","SASB","Responsible behaviour product-design opportunity","SASB identifies product features that incentivise health, safety, and environmentally responsible behaviour, including safer driving, low-emission vehicles, and resource-efficiency-related discounts.","Opportunity","Core","Yes","Yes","Yes","Medium",3,2,"No","No"),
  srro("033","CDSB","Environmental and social dependency disclosure risk","CDSB requires reporting of environmental and social information, including natural, human and social capital dependencies, risks, opportunities, policies, strategies, targets, and performance.","Risk","Upstream","No","Yes","Yes","Medium",2,3,"No","No"),
  srro("034","CDSB","Forward-looking sustainability disclosure opportunity","CDSB guiding principles include forward-looking, clear, consistent, comparable and verifiable environmental/social disclosures in mainstream reports.","Opportunity","Core","No","Yes","Yes","Medium",2,2,"No","No"),
  srro("035","Regulators and peers","Climate-related claims pressure risk","HGI may face increased claims pressure from climate-related events such as flooding, storms, and other natural disasters, especially for property-related lines such as Fire.","Risk","Core","Yes","Yes","Yes","Long",2,4,"Yes","Yes"),
  srro("036","Regulators and peers","Natural catastrophe modelling and reinsurance adequacy risk","HGI may need to assess whether its reinsurance arrangements adequately protect against high-severity events.","Risk","Upstream","Yes","Yes","Yes","Medium",2,3,"Yes","No"),
  srro("037","Regulators and peers","High-risk sector underwriting risk","HGI's exposure to Oil & Gas may create underwriting and liability risks if ESG, environmental, safety, and governance factors are not adequately reflected in pricing and policy terms.","Risk","Core","Yes","Yes","Yes","Medium",3,4,"Yes","Yes"),
  srro("038","Regulators and peers","Responsible investment risk","HGI may face investment portfolio risk if ESG and climate-related factors are not considered in investment decisions.","Risk","Upstream","Yes","Yes","Yes","Long",2,3,"Yes","No"),
  srro("039","Regulators and peers","Customer claims experience risk","HGI may face reputational and customer retention risk if claims are not settled efficiently.","Risk","Downstream","Yes","Yes","Yes","Medium",3,4,"Yes","Yes"),
  srro("040","Regulators and peers","Cybersecurity and data privacy risk","HGI may face operational, regulatory, and reputational risks from cybersecurity or data privacy failures, especially where underwriting, claims, finance, and customer engagement rely on digital systems.","Risk","Core","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("041","Regulators and peers","Value chain ESG risk","HGI may face third-party or supplier-related ESG risks if vendors, brokers, service providers, and partners are not assessed or engaged on sustainability expectations.","Risk","Upstream","No","Yes","Yes","Medium",2,3,"No","No"),
  srro("042","Regulators and peers","Actuarial and insurance liability estimation risk","HGI may face financial reporting and reserving risk if assumptions for insurance liabilities, claims frequency, severity, discount rates, or reinsurance recoveries are not robust.","Risk","Core","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("043","Regulators and peers","Reinsurer credit/default risk","HGI may face risk if reinsurers fail to meet obligations under reinsurance contracts.","Risk","Upstream","Yes","Yes","Yes","Medium",2,4,"Yes","Yes"),
  srro("044","Regulators and peers","Regulatory and ESG governance readiness risk","HGI may face compliance and governance risk if ESG responsibilities, climate risk oversight, and sustainability disclosures are not clearly governed.","Risk","Core","No","Yes","Yes","Medium",3,3,"No","No"),
  srro("045","Regulators and peers","Business continuity risk from extreme events","HGI may face operational disruption risk from extreme events if business continuity arrangements do not explicitly consider natural disasters and climate-related disruptions.","Risk","Core","Yes","Yes","Yes","Short",2,3,"Yes","No"),
  srro("046","Regulators and peers","Climate risk management opportunity","HGI may have an opportunity to strengthen its climate risk framework by integrating climate risk into underwriting, financial planning, stress testing, and business continuity planning.","Opportunity","Core","Yes","Yes","Yes","Medium",2,3,"Yes","No"),
  srro("047","Regulators and peers","Sustainable underwriting opportunity","HGI may have an opportunity to embed ESG considerations into underwriting, especially for high-risk sectors and property-related risks.","Opportunity","Core","Yes","Yes","Yes","Medium",3,3,"Yes","Yes"),
  srro("048","Regulators and peers","Green and sustainable product opportunity","HGI may have an opportunity to develop products that support climate resilience, renewable energy, electric mobility, or other low-carbon activities.","Opportunity","Core","Yes","Yes","Yes","Medium",2,2,"No","No"),
  srro("049","Regulators and peers","Digital claims and operational efficiency opportunity","HGI may have an opportunity to improve customer experience and reduce turnaround time through digital claims processing.","Opportunity","Downstream","Yes","Yes","Yes","Medium",3,3,"Yes","Yes"),
  srro("050","Internal risk register","Reputational risk from adverse publicity","HGI identified adverse publicity as a risk that could result in loss of insured confidence, loss of market influence, reduced staff morale, and loss of stakeholder confidence.","Risk","Downstream","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("051","Internal risk register","Negative brand perception risk","HGI identified mismatch between intended brand image and customer perception, decline in satisfaction/NPS, and increased dissatisfaction as a brand perception risk.","Risk","Downstream","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("052","Internal risk register","Regulatory non-compliance risk in marketing and communications","HGI identified possible fines arising from non-compliance with regulatory requirements, including NAICOM, ARCON, CIIN, and data privacy requirements in marketing activities.","Risk","Downstream","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("053","Internal risk register","Copyright infringement risk","HGI identified potential fines from use of external content without proper licences/permissions and employee unawareness of copyright laws.","Risk","Downstream","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("054","Internal risk register","Data quality and decision-making risk","HGI identified inaccurate data for analysis, where inconsistent or unvalidated inputs may lead to poor decision-making.","Risk","Core","Yes","Yes","Yes","Short",4,3,"Yes","Yes"),
  srro("055","Internal risk register","Data warehouse and automated reporting opportunity","HGI's action plan includes completing an agile data warehouse project with automated data integrity controls, which may improve data reliability and reporting efficiency.","Opportunity","Core","Yes","Yes","Yes","Short",2,2,"No","No"),
  srro("056","Internal risk register","Market competition risk","HGI identified risk that clients may switch to competitors offering better premiums and services.","Risk","Downstream","Yes","Yes","Yes","Short",4,3,"Yes","Yes"),
  srro("057","Internal risk register","Market concentration risk","HGI identified over-reliance on limited clients, sectors, regions, or distribution channels for revenue generation.","Risk","Downstream","Yes","Yes","Yes","Medium",4,3,"Yes","Yes"),
  srro("058","Internal risk register","Channel diversification and underserved-segment product opportunity","HGI's action plan includes diversifying channels through digital platforms and introducing new products for underserved segments in alignment with the NIIRA Act.","Risk","Downstream","Yes","Yes","Yes","Medium",2,3,"No","No"),
  srro("059","Internal risk register","Low renewal ratio risk","HGI identified inability of SBUs to renew renewable policies within the financial year, linked to decrease in future cash flows.","Risk","Downstream","Yes","Yes","Yes","Short",4,3,"Yes","Yes"),
  srro("060","Internal risk register","Credit control and premium remittance risk","HGI identified failure to remit premiums within NAICOM's 30-day grace period as a credit control risk.","Risk","Upstream","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("061","Internal risk register","Liquidity management risk","HGI identified liquidity issues linked to the need for monthly cash flow forecasting to support CFO/FC decision-making.","Risk","Upstream","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("062","Internal risk register","Succession planning and key-person risk","HGI identified lean structures and inadequate successors for key roles, including HR, ERM, and Internal Audit-related succession gaps.","Risk","Core","No","Yes","Yes","Medium",2,3,"No","No"),
  srro("063","Internal risk register","Human capital development opportunity","HGI's action plans include job rotation, cross-training, succession planning implementation, and talent readiness training for identified successors.","Opportunity","Core","Yes","Yes","Yes","Medium",2,2,"No","No"),
  srro("064","Internal risk register","Business system failure and downtime risk","HGI identified risk that critical systems may fail due to outdated infrastructure or technical issues, causing prolonged downtime, disrupted operations, financial loss and reputational damage.","Risk","Core","Yes","Yes","Yes","Short",1,4,"Yes","Yes"),
  srro("065","Internal risk register","Cyber/data breach and data loss risk","HGI identified risks of data corruption/loss due to breach, phishing, insider threats, weak authentication, insecure endpoints, misconfigured cloud services, data leakage, and inadequate access controls.","Risk","Core","Yes","Yes","Yes","Short",4,4,"Yes","Yes"),
  srro("066","Internal risk register","Cybersecurity enhancement opportunity","HGI's action plans include SOC monitoring, immutable backups, continuous vulnerability scanning, MFA expansion, DLP implementation, SSO, network segmentation, and WAF/DMZ implementation.","Opportunity","Core","Yes","Yes","Yes","Short",3,3,"Yes","Yes"),
  srro("067","Internal risk register","Third-party/vendor cybersecurity risk","HGI identified third-party breaches and lack of vendor risk assessments as risks where vendors with system/data access may expose HGI to security breaches.","Risk","Upstream","Yes","Yes","Yes","Short",4,4,"Yes","Yes"),
  srro("068","Internal risk register","Business continuity risk","HGI identified failure to perform essential functions due to operational interruption, with controls including biannual disaster recovery testing and cloud file storage.","Risk","Core","Yes","Yes","Yes","Short",2,3,"Yes","No"),
  srro("069","Internal risk register","Reinsurance support dependency risk","HGI identified rejection of business due to inability to obtain reinsurance support, noting that participation on risk depends largely on necessary reinsurer support.","Risk","Upstream","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("070","Internal risk register","Risk accumulation / flood concentration risk","HGI identified risk accumulation from accepting risks prone to the same loss event, such as flood, where risks concentrate in the same location.","Risk","Core","Yes","Yes","Yes","Medium",1,4,"Yes","Yes"),
  srro("071","Internal risk register","Over-exposure above capacity risk","HGI identified over-exposure risk from retaining risk above the company's capacity.","Risk","Upstream","Yes","Yes","Yes","Medium",1,3,"Yes","No"),
  srro("072","Internal risk register","Inadequate underwriting risk identification","HGI identified failure to identify or accurately assess underwriting risks such as flood, fire load, and theft exposure at insured premises.","Risk","Core","Yes","Yes","Yes","Short",2,4,"Yes","Yes"),
  srro("073","Internal risk register","Pre-loss survey automation opportunity","HGI's action plan includes management approval for pre-loss survey automation and making pre-loss inspection a warranty.","Opportunity","Core","Yes","Yes","Yes","Short",3,2,"No","No"),
  srro("074","Internal risk register","Field survey health and safety risk","HGI identified health and safety risks for survey officers during site duties, with controls including PPE, maintenance and PA cover.","Risk","Core","No","Yes","Yes","Short",2,3,"No","No"),
  srro("075","Internal risk register","Fraudulent and inflated claims risk","HGI identified fraudulent claims, false or inflated claims, and claim-related criminal intent as risks that may lead to financial loss.","Risk","Downstream","Yes","Yes","Yes","Short",2,3,"Yes","No"),
  srro("076","Internal risk register","Claims reserving risk","HGI identified inaccurate claims reserving, which may lead to under- or over-reserving liabilities and affect quarterly/annual financial reporting.","Risk","Core","Yes","Yes","Yes","Short",2,4,"Yes","Yes"),
  srro("077","Internal risk register","Claims processing and customer service disruption risk","HGI identified system glitches affecting claims, UBA and Converge downtimes, and failed payments as claims processing risks.","Risk","Downstream","Yes","Yes","Yes","Short",4,3,"Yes","Yes"),
  srro("078","Internal risk register","Customer data quality risk","HGI identified poor customer contact details on ESKA, including inaccurate or missing email/phone numbers, with 3,060 customer contact records requiring clean-up.","Risk","Downstream","Yes","Yes","Yes","Short",4,2,"Yes","No"),
  srro("079","Internal risk register","Regulatory reporting and AML/CFT compliance risk","HGI identified PEP screening failure, CTR/FTR filing delays, suspicious transaction identification gaps, late regulatory returns, and wrong information in regulatory returns.","Risk","Core","Yes","Yes","Yes","Short",3,4,"Yes","Yes"),
  srro("080","Internal risk register","Compliance automation opportunity","HGI's action plans include PEP screening automation, compliance dashboard monitoring, automated data validation tools, and compliance tools such as Microsoft Purview.","Opportunity","Core","Yes","Yes","Yes","Short",2,3,"Yes","No"),
  srro("081","Internal risk register","Fire hazard and workplace safety risk","HGI identified fire hazards due to electrical faults, human or natural causes, and workplace incidents such as slips, falls or trips.","Risk","Core","Yes","Yes","Yes","Short",2,3,"Yes","No"),
  srro("082","Internal risk register","Vendor non-performance risk","HGI identified vendor non-performance, poor vendor quality, procurement issues, and performance failure of outsourced vendors as risks that may cause delays and service inefficiencies.","Risk","Upstream","Yes","Yes","Yes","Short",2,3,"Yes","No"),
  srro("083","Internal risk register","Product and customer misfit risk","HGI identified inadequate customer profiling and customer-product misfit as a risk, with controls including two-factor onboarding and agent training.","Risk","Downstream","Yes","Yes","Yes","Short",1,2,"Yes","No"),
  srro("084","Internal risk register","Low product adoption and distribution risk","HGI identified low adoption and distribution risk driven by macroeconomic pressure, with mitigation actions including agent/customer incentives, digital channels, USSD and product marketing.","Risk","Downstream","Yes","Yes","Yes","Medium",1,3,"Yes","No"),
  srro("085","Internal risk register","Digital and USSD distribution opportunity","HGI's action plan includes use of digital channels and USSD to support product adoption and distribution.","Opportunity","Downstream","Yes","Yes","Yes","Medium",2,2,"No","No"),
];
