export interface SasbSector {
  id: string;
  name: string;
  industries: string[];
}

export const SASB_TAXONOMY: SasbSector[] = [
  {
    id: "consumer_goods",
    name: "Consumer Goods",
    industries: [
      "Apparel, Accessories & Footwear",
      "Appliance Manufacturing",
      "Building Products & Furnishings",
      "E-Commerce",
      "Household & Personal Products",
      "Multiline and Specialty Retailers & Distributors",
      "Toys & Sporting Goods",
    ],
  },
  {
    id: "extractives_minerals_processing",
    name: "Extractives & Minerals Processing",
    industries: [
      "Coal Operations",
      "Construction Materials",
      "Iron & Steel Producers",
      "Metals & Mining",
      "Oil & Gas – Exploration & Production",
      "Oil & Gas – Midstream",
      "Oil & Gas – Refining & Marketing",
      "Oil & Gas – Services",
    ],
  },
  {
    id: "financials",
    name: "Financials",
    industries: [
      "Asset Management & Custody Activities",
      "Commercial Banks",
      "Consumer Finance",
      "Insurance",
      "Investment Banking & Brokerage",
      "Mortgage Finance",
      "Security & Commodity Exchanges",
    ],
  },
  {
    id: "food_beverage",
    name: "Food & Beverage",
    industries: [
      "Agricultural Products",
      "Alcoholic Beverages",
      "Food Retailers & Distributors",
      "Meat, Poultry & Dairy",
      "Non-Alcoholic Beverages",
      "Processed Foods",
      "Restaurants",
      "Tobacco",
    ],
  },
  {
    id: "health_care",
    name: "Health Care",
    industries: [
      "Biotechnology & Pharmaceuticals",
      "Drug Retailers",
      "Health Care Delivery",
      "Health Care Distributors",
      "Managed Care",
      "Medical Equipment & Supplies",
    ],
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    industries: [
      "Electric Utilities & Power Generators",
      "Engineering & Construction Services",
      "Gas Utilities & Distributors",
      "Home Builders",
      "Real Estate",
      "Real Estate Services",
      "Waste Management",
      "Water Utilities & Services",
    ],
  },
  {
    id: "renewable_resources_alternative_energy",
    name: "Renewable Resources & Alternative Energy",
    industries: [
      "Biofuels",
      "Forestry Management",
      "Fuel Cells & Industrial Batteries",
      "Pulp & Paper Products",
      "Solar Technology & Project Developers",
      "Wind Technology & Project Developers",
    ],
  },
  {
    id: "resource_transformation",
    name: "Resource Transformation",
    industries: [
      "Aerospace & Defense",
      "Chemicals",
      "Containers & Packaging",
      "Electrical & Electronic Equipment",
      "Industrial Machinery & Goods",
    ],
  },
  {
    id: "services",
    name: "Services",
    industries: [
      "Advertising & Marketing",
      "Casinos & Gaming",
      "Education",
      "Hotels & Lodging",
      "Leisure Facilities",
      "Media & Entertainment",
      "Professional & Commercial Services",
    ],
  },
  {
    id: "technology_communications",
    name: "Technology & Communications",
    industries: [
      "Electronic Manufacturing Services & Original Design Manufacturing",
      "Hardware",
      "Internet Media & Services",
      "Semiconductors",
      "Software & IT Services",
      "Telecommunication Services",
    ],
  },
  {
    id: "transportation",
    name: "Transportation",
    industries: [
      "Air Freight & Logistics",
      "Airlines",
      "Auto Parts",
      "Automobiles",
      "Car Rental & Leasing",
      "Cruise Lines",
      "Marine Transportation",
      "Rail Transportation",
      "Road Transportation",
    ],
  },
];

// Comprehensive SASB Materiality Topics Map
export const SASB_MATERIALITY_TOPICS: Record<
  string,
  Record<string, string[]>
> = {
  "Consumer Goods": {
    "Apparel, Accessories & Footwear": [
      "Management of Chemicals in Products",
      "Environmental Impacts in the Supply Chain",
      "Labor Conditions in the Supply Chain",
      "Raw Materials Sourcing",
    ],
    "Appliance Manufacturing": [
      "Product Safety",
      "Product Lifecycle Environmental Impacts",
    ],
    "Building Products & Furnishings": [
      "Energy Management in Manufacturing",
      "Management of Chemicals in Products",
      "Product Lifecycle Environmental Impacts",
      "Wood Supply Chain Management",
    ],
    "E-Commerce": [
      "Hardware & Electronics Management",
      "Data Privacy & Advertising Standards",
      "Data Security",
      "Employee Recruitment, Inclusion & Performance",
      "Labor Practices",
    ],
    "Household & Personal Products": [
      "Water Management",
      "Product Environmental, Health & Safety Performance",
      "Packaging Lifecycle Management",
      "Environmental & Social Impacts of Palm Oil Supply Chain",
    ],
    "Multiline and Specialty Retailers & Distributors": [
      "Energy Management in Retail & Distribution",
      "Data Security",
      "Labor Practices",
      "Workforce Diversity & Inclusion",
      "Product Sourcing, Packaging & Marketing",
    ],
    "Toys & Sporting Goods": [
      "Chemical & Safety Hazards of Products",
      "Labor Conditions in the Supply Chain",
    ],
  },
  "Extractives & Minerals Processing": {
    "Coal Operations": [
      "Greenhouse Gas Emissions",
      "Water Management",
      "Waste & Hazardous Materials Management",
      "Biodiversity Impacts",
      "Rights of Indigenous Peoples",
      "Community Relations",
      "Labor Relations",
      "Workspace Health & Safety",
      "Reserves Valuation & Capital Expenditures",
    ],
    "Construction Materials": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Energy Management",
      "Water Management",
      "Biodiversity Impacts",
      "Workforce Health & Safety",
      "Product Innovation",
    ],
    "Iron & Steel Producers": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Energy Management",
      "Water Management",
      "Waste & Hazardous Materials Management",
      "Workforce Health & Safety",
      "Supply Chain Management",
    ],
    "Metals & Mining": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Energy Management",
      "Water Management",
      "Waste & Hazardous Materials Management",
      "Biodiversity Impacts",
      "Security, Human Rights & Rights of Indigenous Peoples",
      "Community Relations",
      "Labor Relations",
      "Workforce Health & Safety",
      "Business Ethics & Transparency",
    ],
    "Oil & Gas – Exploration & Production": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Water Management",
      "Biodiversity Impacts",
      "Security, Human Rights & Rights of Indigenous Peoples",
      "Community Relations",
      "Workforce Health & Safety",
      "Reserves Valuation & Capital Expenditures",
      "Business Ethics & Transparency",
      "Management of the Legal & Regulatory Environment",
      "Critical Incident Risk Management",
    ],
    "Oil & Gas – Midstream": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Ecological Impacts",
      "Competitive Behavior",
      "Operational Safety, Emergency Preparedness & Response",
    ],
    "Oil & Gas – Refining & Marketing": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Water Management",
      "Waste & Hazardous Materials Management",
      "Workforce Health & Safety",
      "Product Specifications & Clean Fuel Blends",
      "Pricing Integrity & Transparency",
      "Critical Incident Risk Management",
    ],
    "Oil & Gas – Services": [
      "Emissions Reduction Services & Fuels Management",
      "Water Management Services",
      "Chemicals Management",
      "Ecological Impact Management",
      "Workforce Health & Safety",
      "Business Ethics & Payments Transparency",
      "Management of the Legal & Regulatory Environment",
      "Critical Incident Risk Management",
    ],
  },
  Financials: {
    "Asset Management & Custody Activities": [
      "Transparent Information & Fair Advice for Customers",
      "Employee Diversity & Inclusion",
      "Incorporation of Environmental, Social, and Governance Factors in Investment Management & Advisory",
      "Business Ethics",
      "Systemic Risk Management",
    ],
    "Commercial Banks": [
      "Data Security",
      "Financial Inclusion & Capacity Building",
      "Incorporation of Environmental, Social, and Governance Factors in Credit Analysis",
      "Business Ethics",
      "Systemic Risk Management",
    ],
    "Consumer Finance": [
      "Customer Privacy",
      "Data Security",
      "Selling Practices",
    ],
    Insurance: [
      "Environmental Risk Exposure",
      "Policies Designed to Incentivize Responsible Behavior",
      "Plan Performance",
      "Systemic Risk Management",
      "Integration of Environmental, Social, and Governance Factors in Investment Management",
    ],
    "Investment Banking & Brokerage": [
      "Employee Diversity & Inclusion",
      "Incorporation of Environmental, Social, and Governance Factors in Investment Banking & Brokerage Activities",
      "Business Ethics",
      "Professional Integrity",
      "Systemic Risk Management",
    ],
    "Mortgage Finance": [
      "Environmental Risk to Mortgaged Properties",
      "Discriminatory Lending",
      "Legal & Regulatory Environment",
    ],
    "Security & Commodity Exchanges": [
      "Managing Conflicts of Interest",
      "Promoting Transparent & Efficient Capital Markets",
      "Managing Business Continuity & Technology Risks",
    ],
  },
  "Food & Beverage": {
    "Agricultural Products": [
      "Greenhouse Gas Emissions",
      "Energy Management",
      "Water Management",
      "Food Safety",
      "Workforce Health & Safety",
      "Environmental & Social Impacts of Ingredient Supply Chain",
      "Ingredient Sourcing",
    ],
    "Alcoholic Beverages": [
      "Energy Management",
      "Water Management",
      "Responsible Drinking & Marketing",
      "Packaging Lifecycle Management",
      "Environmental & Social Impacts of Ingredient Supply Chain",
      "Ingredient Sourcing",
    ],
    "Food Retailers & Distributors": [
      "Energy Management",
      "Air Quality",
      "Food Waste Management",
      "Data Security",
      "Product Health & Nutrition",
      "Product Labeling & Marketing",
      "Labor Practices",
      "Management of Environmental & Social Impacts in the Supply Chain",
    ],
    "Meat, Poultry & Dairy": [
      "Greenhouse Gas Emissions",
      "Energy Management",
      "Water Management",
      "Waste Management",
      "Food Safety",
      "Workforce Health & Safety",
      "Animal Care & Welfare",
      "Antibiotic Use in Animal Production",
      "Environmental & Social Impacts of Ingredient Supply Chain",
      "Ingredient Sourcing",
    ],
    "Non-Alcoholic Beverages": [
      "Energy Management",
      "Water Management",
      "Health & Nutrition",
      "Product Labeling & Marketing",
      "Packaging Lifecycle Management",
      "Environmental & Social Impacts of Ingredient Supply Chain",
      "Ingredient Sourcing",
    ],
    "Processed Foods": [
      "Energy Management",
      "Water Management",
      "Food Safety",
      "Health & Nutrition",
      "Product Labeling & Marketing",
      "Packaging Lifecycle Management",
      "Environmental & Social Impacts of Ingredient Supply Chain",
      "Ingredient Sourcing",
    ],
    Restaurants: [
      "Energy Management",
      "Water Management",
      "Food & Packaging Waste Management",
      "Food Safety",
      "Nutritional Content",
      "Labor Practices",
      "Supply Chain Management & Food Sourcing",
    ],
    Tobacco: [
      "Public Health",
      "Marketing Practices",
      "Environmental & Social Impacts of Tobacco Supply Chain",
    ],
  },
  "Health Care": {
    "Biotechnology & Pharmaceuticals": [
      "Safety of Clinical Trial Participants",
      "Access to Medicines",
      "Affordability & Pricing",
      "Product Safety",
      "Counterfeit Drugs",
      "Ethical Marketing",
      "Employee Recruitment, Development & Retention",
      "Supply Chain Management",
      "Business Ethics",
    ],
    "Drug Retailers": [
      "Energy Management",
      "Data Security",
      "Patient Privacy & Electronic Health Records",
      "Product Safety",
      "Counterfeit Drugs",
      "Ethical Marketing",
      "Employee Recruitment, Development & Retention",
    ],
    "Health Care Delivery": [
      "Energy Management",
      "Waste Management",
      "Patient Privacy & Electronic Health Records",
      "Quality of Care & Patient Satisfaction",
      "Access for Low-Income Patients",
      "Pricing & Billing Transparency",
      "Employee Health & Safety",
      "Employee Recruitment, Development & Retention",
      "Management of Controlled Substances",
      "Fraud & Unnecessary Procedures",
    ],
    "Health Care Distributors": [
      "Fleet Fuel Management",
      "Product Safety",
      "Counterfeit Drugs",
      "Business Ethics",
    ],
    "Managed Care": [
      "Customer Privacy",
      "Access to Health Care",
      "Plan Performance",
      "Climate Change Impacts on Human Health",
    ],
    "Medical Equipment & Supplies": [
      "Affordability & Pricing",
      "Product Safety",
      "Ethical Marketing",
      "Product Design & Lifecycle Management",
      "Supply Chain Management",
      "Business Ethics",
    ],
  },
  Infrastructure: {
    "Electric Utilities & Power Generators": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Water Management",
      "Waste & Hazardous Materials Management",
      "Energy Resource Planning",
      "Workforce Health & Safety",
      "End-Use Efficiency & Demand",
      "Nuclear Safety & Emergency Management",
      "Grid Resiliency",
    ],
    "Engineering & Construction Services": [
      "Environmental Impacts of Project Development",
      "Structural Integrity & Safety",
      "Workforce Health & Safety",
      "Lifecycle Impacts of Buildings & Infrastructure",
      "Climate Impacts of Business Mix",
      "Business Ethics",
    ],
    "Gas Utilities & Distributors": [
      "Energy Affordability",
      "End-Use Efficiency",
      "Integrity of Gas Delivery Infrastructure",
      "Operational Safety, Emergency Preparedness & Response",
    ],
    "Home Builders": [
      "Land Use & Ecological Impacts",
      "Workforce Health & Safety",
      "Design for Resource Efficiency",
      "Community Impacts of New Developments",
      "Climate Change Adaptation",
    ],
    "Real Estate": [
      "Energy Management",
      "Water Management",
      "Management of Tenant Sustainability Impacts",
      "Climate Change Adaptation",
    ],
    "Real Estate Services": [
      "Sustainability Services",
      "Professional Integrity",
      "Data Privacy & Security",
    ],
    "Waste Management": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Fleet Fuel Management",
      "Management of Leachate & Hazardous Waste",
      "Workforce Health & Safety",
      "Labor Relations",
      "Recycling & Resource Recovery",
    ],
    "Water Utilities & Services": [
      "Energy Management",
      "Effluent Quality Management",
      "Water Scarcity",
      "Drinking Water Quality",
      "Fair Pricing & Access",
      "End-Use Efficiency",
      "Network Resiliency & Impacts of Climate Change",
    ],
  },
  "Renewable Resources & Alternative Energy": {
    Biofuels: [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Water Management",
      "Sourcing & Environmental Impacts of Feedstock",
      "Lifecycle Carbon Emissions",
    ],
    "Forestry Management": [
      "Ecosystem Services & Impacts",
      "Rights of Indigenous Peoples",
      "Climate Change Adaptation",
    ],
    "Fuel Cells & Industrial Batteries": [
      "Energy Management",
      "Workforce Health & Safety",
      "Product Efficiency",
      "Product End-of-Life Management",
      "Materials Sourcing",
    ],
    "Pulp & Paper Products": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Energy Management",
      "Water Management",
      "Fiber Sourcing",
    ],
    "Solar Technology & Project Developers": [
      "Energy Management in Manufacturing",
      "Water Management in Manufacturing",
      "Hazardous Materials Management",
      "Community Relations",
      "Ecological Impacts of Project Development",
      "Product Lifecycle Management",
      "Materials Sourcing",
    ],
    "Wind Technology & Project Developers": [
      "Ecological Impacts of Project Development",
      "Materials Sourcing",
      "Materials Efficiency",
    ],
  },
  "Resource Transformation": {
    "Aerospace & Defense": [
      "Energy Management",
      "Hazardous Waste Management",
      "Product Safety",
      "Fuel Economy & Emissions in Use-phase",
      "Materials Sourcing",
      "Business Ethics",
    ],
    Chemicals: [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Energy Management",
      "Water Management",
      "Hazardous Waste Management",
      "Community Relations",
      "Workforce Health & Safety",
      "Product Design for Use-phase Efficiency",
      "Safety & Environmental Stewardship of Chemicals",
      "Genetically Modified Organisms",
      "Management of the Legal & Regulatory Environment",
      "Operational Safety, Emergency Preparedness & Response",
    ],
    "Containers & Packaging": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Energy Management",
      "Water Management",
      "Waste Management",
      "Product Safety",
      "Product Lifecycle Management",
      "Materials Sourcing",
    ],
    "Electrical & Electronic Equipment": [
      "Energy Management",
      "Hazardous Waste Management",
      "Product Safety",
      "Product Lifecycle Management",
      "Materials Sourcing",
      "Business Ethics",
    ],
    "Industrial Machinery & Goods": [
      "Energy Management",
      "Employee Health & Safety",
      "Fuel Economy & Emissions in Use-phase",
      "Materials Sourcing",
      "Remanufacturing Design & Services",
    ],
  },
  Services: {
    "Advertising & Marketing": [
      "Advertising Integrity",
      "Data Privacy",
      "Workforce Diversity & Inclusion",
    ],
    "Casinos & Gaming": [
      "Energy Management",
      "Responsible Gaming",
      "Anti-Money Laundering",
    ],
    Education: [
      "Data Security",
      "Data Privacy",
      "Quality of Education & Gainful Employment",
      "Marketing & Recruiting Practices",
    ],
    "Hotels & Lodging": [
      "Energy Management",
      "Water Management",
      "Ecological Impacts",
      "Labor Practices",
    ],
    "Leisure Facilities": [
      "Energy Management",
      "Ecological Impacts",
      "Customer Safety",
      "Labor Practices",
    ],
    "Media & Entertainment": [
      "Journalistic Integrity & Sponsorship Identification",
      "Pluralism in Media Content",
      "Intellectual Property Protection & Media Piracy",
      "Data Privacy & Advertising Standards",
    ],
    "Professional & Commercial Services": [
      "Data Security",
      "Workforce Diversity & Engagement",
      "Professional Integrity",
    ],
  },
  "Technology & Communications": {
    "Electronic Manufacturing Services & Original Design Manufacturing": [
      "Water Management",
      "Waste Management",
      "Labor Practices",
      "Product Structure & Lifecycle Management",
      "Supply Chain Management",
    ],
    Hardware: [
      "Product Security",
      "Employee Diversity & Inclusion",
      "Product Lifecycle Management",
      "Supply Chain Management",
      "Materials Sourcing",
    ],
    "Internet Media & Services": [
      "Environmental Footprint of Hardware Infrastructure",
      "Data Privacy & Advertising Standards",
      "Data Security",
      "Employee Recruitment, Inclusion & Performance",
      "Intellectual Property Protection & Competitive Behavior",
    ],
    Semiconductors: [
      "Greenhouse Gas Emissions",
      "Energy Management in Manufacturing",
      "Water Management",
      "Waste Management",
      "Employee Health & Safety",
      "Product Lifecycle Management",
      "Materials Sourcing",
      "Intellectual Property Protection & Competitive Behavior",
      "Employee Recruitment, Development & Retention",
    ],
    "Software & IT Services": [
      "Environmental Footprint of Hardware Infrastructure",
      "Data Privacy & Freedom of Expression",
      "Data Security",
      "Employee Recruitment, Inclusion & Performance",
      "Intellectual Property Protection & Competitive Behavior",
      "Managing Systemic Risks from Technology Disruptions",
    ],
    "Telecommunication Services": [
      "Environmental Footprint of Operations",
      "Data Privacy",
      "Data Security",
      "Product End-of-life Management",
      "Competitive Behavior & Open Internet",
      "Managing Systemic Risks from Technology Disruptions",
    ],
  },
  Transportation: {
    "Air Freight & Logistics": [
      "Greenhouse Gas Emissions",
      "Labor Practices",
      "Employee Health & Safety",
      "Supply Chain Management",
      "Accident & Safety Management",
    ],
    Airlines: [
      "Greenhouse Gas Emissions",
      "Labor Practices",
      "Competitive Behavior",
      "Accident & Safety Management",
    ],
    "Auto Parts": [
      "Energy Management",
      "Waste Management",
      "Product Safety",
      "Design for Fuel Efficiency",
      "Materials Sourcing",
      "Competitive Behavior",
    ],
    Automobiles: [
      "Fuel Economy & Use-phase Emissions",
      "Product Safety",
      "Labor Practices",
      "Materials Sourcing",
    ],
    "Car Rental & Leasing": [
      "Fleet Fuel Economy & Use-phase Emissions",
      "Labor Practices",
    ],
    "Cruise Lines": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Ecological Impacts",
      "Employee Health & Safety",
      "Accident & Safety Management",
    ],
    "Marine Transportation": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Ecological Impacts",
      "Employee Health & Safety",
      "Business Ethics",
      "Accident & Safety Management",
    ],
    "Rail Transportation": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Employee Health & Safety",
      "Competitive Behavior",
      "Accident & Safety Management",
    ],
    "Road Transportation": [
      "Greenhouse Gas Emissions",
      "Air Quality",
      "Driver Working Conditions",
      "Accident & Safety Management",
    ],
  },
};
